### ISSUE TITLE
Add thickness of the annotations as parameters

### ISSUE THREAD

**Issue by lfoppiano** [lfoppiano/streamlit-pdf-viewer#14]
The annotations might be too thick depending on how large the PDF document is rendered (size, etc.)

**Comment by lfoppiano** [comment]
value = 1

![image](https://github.com/lfoppiano/streamlit-pdf-viewer/assets/15426/83b178eb-e85a-456c-a6e4-ad6572fe6f71)


value = 10 
![image](https://github.com/lfoppiano/streamlit-pdf-viewer/assets/15426/92b710ed-379a-40ff-96e7-04d359d4aafb)

**Comment by t29mato** [comment]
This is my local machine. Which line have you changed?
<img width="2338" alt="image" src="https://github.com/lfoppiano/streamlit-pdf-viewer/assets/30012556/1546014b-eaef-425e-9fb6-2c8d5bf816cd">

**Comment by lfoppiano** [comment]
OK. I forgot to rebuild the bloody frontend part... 😭
