### ISSUE TITLE
Add text layer on top of the canvases

### ISSUE THREAD

**Issue by lfoppiano** [lfoppiano/streamlit-pdf-viewer#16]
At the moment we use canvas to build the pdf viewer, however in previous versions the text was selectable

https://github.com/lfoppiano/grobid-superconductors/blob/master/src/main/resources/web/grobid/grobid-superconductors.js

**Comment by lfoppiano** [comment]
@t29mato it seems that this issue might be useful if we want to allow people to copy-paste the rendered text from the viewer. Also in the view of perhaps a future integration in starry data, I was wondering, how much time might would be required to implement it, given we have a working prototype in the grobid JS?

**Comment by lfoppiano** [comment]
I've been trying to implement this: https://www.sitepoint.com/custom-pdf-rendering/#renderingtextlayers 

but it's currently stuck due to a problem with the build

**Comment by lfoppiano** [comment]
@t29mato I did fix the scaling of the text layers in eb89aae6b6b137aae99d449e6a8fc25123b5da45 but now the annotations have disappeared... 😭 

<img width="788" alt="image" src="https://github.com/lfoppiano/streamlit-pdf-viewer/assets/15426/c8800966-f6c9-42de-bab2-d2a8488d5246">

**Comment by t29mato** [comment]
I'll check it out

**Comment by lfoppiano** [comment]
Yes, so the issue is that we want to see the annotations but we want to have the transparent text layers on top.

No idea how to do that. I'm already surprised I came this far 😅😅😅

**Comment by t29mato** [comment]
This is difficult.
Setting the `z-index` of the `textLayer` class to 11 or higher improves the selection UI, but it prevents annotations from being clickable or hoverable...

**Comment by t29mato** [comment]
The final solution might be to separate the annotation click mode and text selection mode into different modes, but this is a compromise.

**Comment by lfoppiano** [comment]
I think with sparse annotations should be no problem. This example is full of annotations and does not respect the reality IMHO. 🤔
