### ISSUE TITLE
Add Type Validation for `width` and `height` Parameters in `pdf_viewer` Function

### ISSUE THREAD

**Issue by t29mato** [lfoppiano/streamlit-pdf-viewer#18]
Currently, the `pdf_viewer` function accepts `width` and `height` parameters, which are expected to be integers or None. However, there's no explicit type checking in place.

**Comment by lfoppiano** [comment]
Why the `width` has a default value of 700?

**Comment by t29mato** [comment]
There is no exact reason.
I have thought that 30px is too narrow and 2000px is too wide.
We can change these values to more reasonable numbers.
I don't know which number is the bese, though.
Do you have any idea?

**Comment by lfoppiano** [comment]
No, if we don't pass any default value, what will happen?
