### ISSUE TITLE
Scroll to specific pages

### ISSUE THREAD

**Issue by lfoppiano** [lfoppiano/streamlit-pdf-viewer#24]
I opened a new issue to discuss what was mentioned in https://github.com/lfoppiano/streamlit-pdf-viewer/issues/22#issuecomment-1934000304.

Is it possible to scroll down a specified page? 

One possible use case could be that the user wants to link information extracted from the document with specific pages.

**Comment by Odrec** [comment]
In my use case this will be really helpful

**Comment by lfoppiano** [comment]
https://discuss.streamlit.io/t/how-can-i-use-an-auto-scroll-to-the-bottom-of-the-page/39650/7

**Comment by lfoppiano** [comment]
@Odrec  I've released version `0.0.18-dev0` that should implement this feature. Please have a go and let me know if you have feedback. 

Please see [here](https://github.com/lfoppiano/streamlit-pdf-viewer/issues/61#issuecomment-2295365514) for more details.

**Comment by ghirardinicola** [comment]
Tested and worked fine for me, waiting for the stable release ;)

**Comment by rupinderpascal** [comment]
Hey @lfoppiano  an issue that i noticed while working with this is that when height is specified for the pdf viewer the scrolling doesn't work.
Removing the height parameter scrolls the pdf right

**Comment by lfoppiano** [comment]
Hi @rupinderpascal, thanks for reporting that, we've tracking that regression in #83

**Comment by lfoppiano** [comment]
@rupinderpascal we've provisionally released version 0.0.23-dev0 which should fix the issue, please follow up in #83.
