### ISSUE TITLE
Component Error message on browser when trying to display a pdf

### ISSUE THREAD

**Issue by Odrec** [lfoppiano/streamlit-pdf-viewer#26]
I'm getting this error on my browser when trying to display a pdf (any)

```
Component Error
Message: TypeError: Cannot read properties of null (reading 'length')
```

This is my code:

```
from streamlit_pdf_viewer import pdf_viewer


container_pdf, container_chat = st.columns([50, 50])


with container_pdf:
    pdf_file = st.file_uploader("Upload PDF file", type=('pdf'))

    if pdf_file:
        binary_data = pdf_file.getvalue()
        pdf_viewer(input=binary_data,
                   width=700)
```

I tried one of the PDFs on the app [here](https://structure-vision.streamlit.app/) and the display works fine so it's not the PDF.

I'm using:
python==3.12
streamlit==1.31.0

**Comment by lfoppiano** [comment]
Hi @Odrec, 
    which version of streamlit-pdf-viewer are you using in your application? 
    
If you call the pdf-viewer with `rendering=legacy_iframe` can you see the PDF document?

**Comment by Odrec** [comment]
Hi @lfoppiano 

The version I'm using is the latest:

streamlit-pdf-viewer==0.0.6.

I tried using that option you suggested but I get the same error. I managed to display the pdf like this with no issue:

```
        binary_data = pdf_file.getvalue()
        base64_pdf = base64.b64encode(binary_data).decode('utf-8')

        # Embed PDF in HTML
        pdf_display = (F'<iframe src="data:application/pdf;base64,{base64_pdf}" '
                       F'width="100%" height="1000" type="application/pdf"></iframe>')

        # Display file
        st.markdown(pdf_display, unsafe_allow_html=True)

```

**Comment by lfoppiano** [comment]
@Odrec which browser are you using?

**Comment by lfoppiano** [comment]
OK, I found the problem. There is indeed a bug. Could you try to call the viewer by adding `pages_to_render=[]`? 

```
        pdf_viewer(input=binary_data,
                   width=700, pages_to_render=[])
```

**Comment by Odrec** [comment]
> I think I found one problem, but the error message I received is different from yours. Could you update to version 0.0.7 and let me know if your code works?

It works now with the latest version :)

**Comment by lfoppiano** [comment]
I'm going to close this issue. Feel free to reopen or comment, if needed.
