### ISSUE TITLE
Infinite Execution of onUpdated Method

### ISSUE THREAD

**Issue by t29mato** [lfoppiano/streamlit-pdf-viewer#28]
The `onUpdated` method seems to be executing infinitely. 

## how to visualize this

```javascript
// Reference code in PdfViewer.vue, the line is around 156
    onUpdated(() => {
      console.log('onUpdated')
      setFrameHeight()
    });
```

## Environment

streamlit-pdf-viewer 0.6

## Screencapture

https://github.com/lfoppiano/streamlit-pdf-viewer/assets/30012556/328fecc5-8b90-4e78-9199-6870dee286e6

**Comment by lfoppiano** [comment]
Looks good now
