### ISSUE TITLE
Show annotations on the PDF document

### ISSUE THREAD

**Issue by lfoppiano** [lfoppiano/streamlit-pdf-viewer#3]
The usage should be something like: 

```
 st.viewer.push_annotation(annotations)
```

annotations should contains data in the following format: 

```
annotation = [
{
"page": x, 
"x": 1 
"y": 3
"height": 10
"width": 10
"color": blue
}
...
]
```

Tasks: 
- [x] load annotations
- [x] show annotations
- [x] ~~add two more methods~~
  - [x] ~~set_annotations(annotations=[]): set the annotations and draw them on the PDF~~
  - [x] ~~clear_annotations(): remove the annotations from the pdf~~
- [x] [fix https://github.com/lfoppiano/streamlit-pdf-viewer/issues/3#issuecomment-1863793941](https://github.com/lfoppiano/streamlit-pdf-viewer/issues/17)

**Comment by lfoppiano** [comment]
In [this document](https://github.com/lfoppiano/streamlit-pdf-viewer/files/13722583/hatakeyama2023prompt.pdf) there seems to be a problem with the annotations. 

![image](https://github.com/lfoppiano/streamlit-pdf-viewer/assets/15426/90fa9b72-b034-4a56-8cca-ef1c8506ce81)

We could ask each page heights and width as an optional argument of the main method

**Comment by lfoppiano** [comment]
This is what grobid could provide as information about pages: 


```xml
    <facsimile>
        <surface n="1" ulx="0.0" uly="0.0" lrx="634.32" lry="833.04"/>
        <surface n="2" ulx="0.0" uly="0.0" lrx="595.276" lry="841.89"/>
        <surface n="3" ulx="0.0" uly="0.0" lrx="595.276" lry="841.89"/>
        <surface n="4" ulx="0.0" uly="0.0" lrx="595.276" lry="841.89"/>
        <surface n="5" ulx="0.0" uly="0.0" lrx="595.276" lry="841.89"/>
        <surface n="6" ulx="0.0" uly="0.0" lrx="595.276" lry="841.89"/>
        <surface n="7" ulx="0.0" uly="0.0" lrx="595.276" lry="841.89"/>
        <surface n="8" ulx="0.0" uly="0.0" lrx="595.276" lry="841.89"/>
        <surface n="9" ulx="0.0" uly="0.0" lrx="595.276" lry="841.89"/>
        <surface n="10" ulx="0.0" uly="0.0" lrx="595.276" lry="841.89"/>
        <surface n="11" ulx="0.0" uly="0.0" lrx="595.276" lry="841.89"/>
        <surface n="12" ulx="0.0" uly="0.0" lrx="595.276" lry="841.89"/>
        <surface n="13" ulx="0.0" uly="0.0" lrx="595.276" lry="841.89"/>
        <surface n="14" ulx="0.0" uly="0.0" lrx="595.276" lry="841.89"/>
        <surface n="15" ulx="0.0" uly="0.0" lrx="595.276" lry="841.89"/>
        <surface n="16" ulx="0.0" uly="0.0" lrx="595.276" lry="841.89"/>
        <surface n="17" ulx="0.0" uly="0.0" lrx="595.276" lry="841.89"/>
    </facsimile>
```

**Comment by t29mato** [comment]
To show annotations generated by GROBID, which branch or environment are you using?

What I use is below
- https://github.com/lfoppiano/streamlit-pdf-viewer/tree/show-annotations
- https://github.com/lfoppiano/document-qa/tree/add-pdf-viewer

Now, I am trying to integrate the `show annotations` button.
https://github.com/lfoppiano/document-qa/commit/b325c610c654505266d5a7dbef11439015bf4eed
<img width="1676" alt="Screenshot 2024-01-10 at 19 56 45" src="https://github.com/lfoppiano/streamlit-pdf-viewer/assets/30012556/c6e4ef7c-733a-44aa-a572-b4df70501711">

**Comment by lfoppiano** [comment]
The branch `show-annotations` was already merged, so you can keep using it or create a new one. 
For testing, you should use the https://github.com/lfoppiano/structure-vision project instead of document-qa.
