### ISSUE TITLE
Add annotation format in the documentation 

### ISSUE THREAD

**Issue by lfoppiano** [lfoppiano/streamlit-pdf-viewer#31]
As commented here: https://discuss.streamlit.io/t/streamlit-pdf-viewer/57768/3

> it would be useful if you show how to format the annotations in the readme. Like a short example. It is stated that it is a list of dictionaries but what should the dictionary look like.

**Comment by lfoppiano** [comment]
@Odrec, could you check at the PR #32 if it is clear?

**Comment by Odrec** [comment]
Yep! got it!

**Comment by lfoppiano** [comment]
I close this for the moment. Feel free to reopen if you have further questions about the annotations.
