### ISSUE TITLE
Support URL as input 

### ISSUE THREAD

**Issue by lfoppiano** [lfoppiano/streamlit-pdf-viewer#33]
Supplying an URL http/https should download the file and show it

**Comment by samuelrhjoseph** [comment]
this would be really really useful!

**Comment by lfoppiano** [comment]
Hi @samuelrhjoseph, I'm afraid that this functionality in the pdf_viewer cannot be implemented because streamlit reloads the page at each interaction causing the pdf_viewer to reload and to try to download the file. 
This functionality should be implemented in the streamlit application which can cache the document and avoid unnecessary computation and downloads.

**Comment by ArthurTech123** [comment]
I found it is a low efficacy way to slove the problem but it work
so this method is workable enough but just enough.
