### ISSUE TITLE
Problems displaying pdf in Streamlit Cloud

### ISSUE THREAD

**Issue by trbtl** [lfoppiano/streamlit-pdf-viewer#43]
Problem with displaying a pdf in Streamlit Cloud. The pdf displays correctly when I run it locally, but no luck with displaying it on Streamlit Cloud. Any ideas?

**Comment by lfoppiano** [comment]
could you share which browser you're using and, if possible,  the url on the streamlit cloud?

**Comment by trbtl** [comment]
I'm using the chrome browser as it is widely used.  I've deployed to both the Streamlit and Azure cloud to see if it was provider specific issue,, but no joy on either one.
The Git repository is: https://github.com/trbtl/trbtl
Streamlit cloud: https://kidneychat.streamlit.app/
Azure cloud: https://kidneychat.azurewebsites.net/

A little context: We are a nonprofit group called The Road Back To Life. We provide support and help for kidney disease patients through Support Group meetings via Zoom as well as personal mentoring.  We have a social media presence and our website at https://www.kidneysupportgroup.org/. This chat app is another possible avenue we'd like to make availabile to people who have questions about kidney disease.
Thank you,
Bob

**Comment by trbtl** [comment]
I'm using the chrome browser as it is widely used. I've deployed to both the Streamlit and Azure cloud to see if it was provider specific issue,, but no joy on either one.
The Git repository is: https://github.com/trbtl/trbtl
Streamlit cloud: https://kidneychat.streamlit.app/
Azure cloud: https://kidneychat.azurewebsites.net/
The specific pages are:
https://github.com/trbtl/trbtl/blob/main/pages/4_References.py
https://kidneychat.azurewebsites.net/References
https://kidneychat.streamlit.app/References
A little context: We are a nonprofit group called The Road Back To Life. We provide support and help for kidney disease patients through Support Group meetings via Zoom as well as personal mentoring. We have a social media presence and our website at https://www.kidneysupportgroup.org/. This chat app is another possible avenue we'd like to make availabile to people who have questions about kidney disease.
Thank you,
Bob

**Comment by lfoppiano** [comment]
Hi @trbtl, 
    thanks for sharing the details. 

I apologise, in this period I cannot work on this project full time so all fixes are delayed, as I would prefer to merge them once they are reviewed. 

I believe that the PR #38 should solve your problem. 

In the meantime, I can suggest you some ways to try to make it work with version 0.0.7. 
I think that if you specify the height you should be able to see the PDF with Chrome. 
I did not test it, I based this suggestion on the fact that the tests that are failing on the main branch using chromium (we can approximate it to Chrome) are the ones where the pdf_viewer is called without height argument.

**Comment by lfoppiano** [comment]
I tested with Brave browser and Chromium (I don't have Chrome, unfortunately) and I could not reproduce the same issue you had. @trbtl did you have any luck in providing the height parameter?

**Comment by trbtl** [comment]
Yes, I set a height, and it appears to work. I’m working on finding the optimal setting that works with different screen sizes. I’ll let you know how it goes.

Thank you,
Bob

**Comment by lfoppiano** [comment]
With 0.0.9, without the height parameter, it should work, but to confirm could you give it a try?

**Comment by trbtl** [comment]
I’ll give it a try and let you know how it goes.

-Bob

**Comment by trbtl** [comment]
Luca,

I’m sorry, after upgrading to 0.0.9, we’re back to the original issue of some pdfs won’t display unless you click on the calling button a second time.  Setting a height seems to cure the issue like before.  Thank you for your effort, I’d be happy to continue testing anything you want.

-Bob

**Comment by lfoppiano** [comment]
@trbtl Thanks for testing quickly.  
The height being necessary is a separate issue I will deal with in #41.

**Comment by lfoppiano** [comment]
@trbtl I've released version 0.0.10, it should resolve the problem occurring when the height is not specified. Could you try it out, please?

**Comment by trbtl** [comment]
Will do.

Thanks
Bob

**Comment by trbtl** [comment]
Luca,

It works!  WoHoo! Thank you!  You can check it out at https://kidneyfaq.streamlit.app/.

Request: If you get a chance, my only wish to improve the tool is to have the hyperlinks work. I know you’re very busy so consider this a wish 😊,

Thanks again,
Bob
