### ISSUE TITLE
Scroll to specific coordenates

### ISSUE THREAD

**Issue by igormicadei** [lfoppiano/streamlit-pdf-viewer#55]
I couldn't find this feature...

I have a document and a list of annotations. It would be nice if there were a feature to scroll the document to a specific coordinate. This way, when I select a specific annotation, it would jump to that point in the document.

**Comment by lfoppiano** [comment]
Hi @igormicadei, the scroll is not implemented at the moment. It's a feature nice to have but hard to implement with streamlit. If you have an idea on how to do it feel free to drop us a PR

**Comment by lfoppiano** [comment]
@igormicadei I've released version 0.0.18-dev0 that should implement this feature. Please have a go and let me know if you have feedback. 

Please see [here](https://github.com/lfoppiano/streamlit-pdf-viewer/issues/61#issuecomment-2295365514) for more details.
