### ISSUE TITLE
PDF Viewer isn't loading when called in tabs or expanders

### ISSUE THREAD

**Issue by hamdi3** [lfoppiano/streamlit-pdf-viewer#56]
When trying to render PDFs in a streamlit tab, it only works for the tab that is selected when the page loads. 
I've also seen the same behavior when rendering inside streamlit extenders.

The code is as follows:
```
paths = glob("../../*/*.pdf")
for i, (path, tab) in enumerate(zip(paths, streamlit.tabs(paths))):
  with tab:
      with streamlit.container(border=True):
          pdf_viewer(path, height = 490, render_text = True, key=f"key_{i}")
          streamlit.info(f"read from {path}")
```

What I've tried so far:
- Wrote an extra function with pdf_viewer as return value.
- Stored multiple instances of pdf_viewer in a dict and variables to make sure it wasn't an overwrite issue. (Even tried to save them in the session parameters).
- Tried all available rendering methods for the function.

I would really appreciate it if you have a workaround.

Thanks in advance!

**EDIT**: I've seen the other Issue with streamlit tabs so I was wondering if it is in your plans to fix it later and if it's the same issues with expenders.

**Comment by lfoppiano** [comment]
This should be solved in the PR #58. If you could test it that would be good. The instructions to install the modified version are [here](https://github.com/lfoppiano/streamlit-pdf-viewer/issues/54#issuecomment-2263813511).

Thanks a lot

**Comment by lfoppiano** [comment]
I've released the version 0.0.15. It's not yet officially published, but it's on pypi. Could you please give it a try?

**Comment by hamdi3** [comment]
Here's the same results I've commented on the PR
Thanks for the update and the new version :)
After testing it myself i came across the following:

    The width of the pdf viewer is automatically set to view at least the full page, meaning you can't increase in a way it would zoom in showing half a page in full width (This was possible before).
    Setting render_text to true would cause the following error m.renderTextLayer is not a function.
    On the bright side it works with tabs now :)

**Comment by lfoppiano** [comment]
@hamdi3 feel free to close this issue
