### ISSUE TITLE
How to get the selected text

### ISSUE THREAD

**Issue by StudyingLover** [lfoppiano/streamlit-pdf-viewer#62]
Hi, I'm building a readpaper helper, and I set `render_text` is True, but I need to get the selected content from the web. Can you help to solve this issue?

**Comment by lfoppiano** [comment]
Hi @StudyingLover, sorry I don't understand the issue. Could you please explain it more in details?

**Comment by StudyingLover** [comment]
ok, for example, I select some words now
![image](https://github.com/user-attachments/assets/66493ff9-5d01-41e2-8772-d2d37a16ffca)

I wonder how to retrieve these words in the code

**Comment by lfoppiano** [comment]
This component is a viewer, if you want to extract text from documents there are other tools to do that. You can check the code of [this application](https://structure-vision.streamlit.app/) that I use as a showcase for this component.

**Comment by StudyingLover** [comment]
ok thanks
