### ISSUE TITLE
Annotations are dependent on knowing the page size from Grobid

### ISSUE THREAD

**Issue by sharma-n** [lfoppiano/streamlit-pdf-viewer#67]
I have annotations in pixel space from a completely different place, which reads the page size of the PDF as something completely different from Grobid. Scaling the x, y, width and heights to fit the Grobid values would be simple **if only** I knew what the size of the page according to Grobid was.

Is there a way to find that out (without actually running Grobid on a PDF)?

It would be best if the annotations were expected to be in the width/height of the pdf_viewer, instead of the Grober width/heights.

**Comment by lfoppiano** [comment]
Hi @sharma-n, 
 thank you for reporting an issue and your interest in this component :-) 

I don't think the annotations are dependent on grobid's page size. It is possible that the annotations are inaccurately extracted (by any tool).

Could you please provide some examples, including PDF and the resulting coordinates that you extracted?

**Comment by sharma-n** [comment]
Hi,
As an example I am attaching [this PDF](https://github.com/user-attachments/files/16903512/CPPIB-Impact.report.pdf).
From a third tool, I get the following annotation for the table on page 5:
```
annotation = {"page":5
"coordinates":{
  "x":97.6
  "y":264.3
  "width":1454.7
  "height":773
  "layout_height":2339
  "layout_width":1654
}}
```
When I use these annotations directly to show them using the pdf_viewer, the annotation is out of the boundaries of the page.

I then extracted the "size of the page" from Grobid (using their docker image), which gave me the size as `(595.276, 841.89)`.

Once I got these, I used the following piece of code to visualize the PDF:
```{python}
pdf_viewer(
    input=pdf,
    width = 1200,
    pages_to_render=[5],
    annotations = [{
        'page': annotation['page'],
        'x': annotation['x']/annotation['layout_width']*595.276,
        'y': annotation['y']/annotation['layout_height']*841.89,
        'width': annotation['width']/annotation['layout_width']*595.276,
        'height': annotation['height']/annotation['layout_height']*841.89,
        'color': 'green',
    }],
    annotation_outline_size=4
)
```
giving me the perfect bounding box below:
<img width="805" alt="image" src="https://github.com/user-attachments/assets/b1fdace9-e6ee-4ec5-a69d-d9f7c8a4adbc">

Now this works, but that's becuase I ran the Grobid library on the PDF. Generally, I would prefer to just get access to the values `(595.276, 841.89)` somehow, or even better not need them.

**Comment by lfoppiano** [comment]
Sorry, maybe I'm not understanding properly the issue here. 
Can't you just get the size of the page from the external tool you're using and keep the same "formula" to calculate the exact point in the PDF document? 
I think most of the tools could provide you that.

**Comment by sharma-n** [comment]
I think the `annotations` argument in `pdf_viewer` expects the x,y coordinates to be in between (0, 595.276) and (0,841.89) respectively. If I use the original coordinates that I have, they will be between (0, 1654) and (0, 2339) respectively.

Not sure if I'm the one missing something obvious here 😟

**Comment by lfoppiano** [comment]
I don't think the page size changes from one application to another. Are you sure you're pulling the correct values? 

E.g. I've made a quick test with PyMyPDF and picking up the first page information are the same as you pulled out from Grobid: 

```
fitz.open(input_temporary_file)[0].rect
```

I think is `rect` but honestly, I could not find a proper way to extract the page size from the documentation, anyway see the values in the debugger of the first page: 

<img width="697" alt="image" src="https://github.com/user-attachments/assets/f0371c1d-cd23-4007-98d6-4ee4a6946eb7">

**Comment by sharma-n** [comment]
Hmm ok probably there's some scaling going on somewhere in the other tool. Will just use `pypdf` meanwhile to get the correct sizes. Thanks for the help!
